print ("tugas python")
print ()
nama = input("masukan nama anda :")
panggilan = input("masukan nama panggilan :")
nim = input("masukan nim :")
tglhr = input("masukan tanggal lahir :")
tmlhr = input("masukan tempat lahir :")
tlpn = input("masukan nomor telepon :")
alamat = input("masukan alamat :")
umur = input("masukan umr anda :")
print()
print("assalamu'alaikum")
print()
print("let me introduce my self, my name is",nama,"but you can cal me",panggilan,"my nim is",nim,"i was born",tglhr,"and i am",umur,"years old, i am very gold if you want to invite my in",alamat,"so, don't forget to call me before, and this my number",tlpn,)
print()
print("Thank you")